### ISSUE TITLE
Pushes to main should run `generate` and create a PR with potential diff

### ISSUE THREAD

**Issue by RafalWilinski** [Stedi/registry#21]
Automation first.

**Comment by siddharthsarda** [comment]
Personally I think until we have the mappings landing page live, we should put this on hold. I very much suspect that how we have our schemas right now will change based on demands of the landing page. Once the landing page is live, we can then approach this.

The reason I say this is because currently we have versions in the directory structure, however I dont think we would want to change the registry landing page that frequently.
